#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install nginx

sudo bash -c 'echo "server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.google.com/;
    }

    location / {
        return 200 \"Hello World!\";
    }
}" > /etc/nginx/sites-available/hello'

sudo ln -s /etc/nginx/sites-available/hello /etc/nginx/sites-enabled/

sudo rm /etc/nginx/sites-enabled/default

sudo service nginx restart
