#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install -y nginx

HOSTNAME=$(hostname)

sudo touch /etc/nginx/conf.d/custom-http-response-header.conf

sudo bash -c "cat << EOF > /etc/nginx/conf.d/custom-http-response-header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root   /etc/nginx/html;   
    index  index.html index.htm;

    add_header X-Served-By $HOSTNAME;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
}
EOF"

sudo rm /etc/nginx/sites-enabled/default

sudo service nginx start
