#!/usr/bin/env bash
#A Bash script that generates a MySQL dump and creates a compressed archive out of it.

DATE=$(date +%d-%m-%Y)

MYSQL_ROOT_PASSWORD="$1"

BACKUP_FILE="backup.sql"

ARCHIVE_NAME="$DATE.tar.gz"

mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > "$BACKUP_FILE"

tar -czf "$ARCHIVE_NAME" "$BACKUP_FILE"
