#!/usr/bin/env bash
#This script takes an argument and run the whoami command under the user passed as an argument

if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the username from the argument
username=$1

# Check if the user exists and has a home directory
if id "$username" >/dev/null 2>&1 && [ -d "/home/$username" ]; then
  # Run the whoami command under the specified user with HOME
  su - "$username" -c "whoami"
else
  # Run the whoami command under the specified user without HOME
  su "$username" -c "whoami"
fi
