#!/usr/bin/env bash
#This script takes an argument and run the whoami command under the user passed as an argument

if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

username=$1

if id "$username" >/dev/null 2>&1; then
  if [ -d "/home/$username" ]; then
    su - "$username" -c "whoami"
  else
    echo "$username"
  fi
else
  echo "User does not exist"
fi
