#!/usr/bin/env bash
#This script takes an argument and run the whoami command under the user passed as an argument

if [ $# -eq 0 ]; then
  echo "Error: Please provide a username as an argument."
  exit 1
fi

username="$1"

sudo -u "$username" whoami
